export const CLIENT_FORM_COLUMNS = {
  organization: {
    type: 'TEXT',
    nullable: true,
    label: 'Организация',
    placeholder: 'Введите название организации',
  },
  name: {
    type: 'TEXT',
    nullable: true,
    label: 'Наименование',
    placeholder: 'Введите наименование',
  },
  phone_number: {
    type: 'TEXT',
    nullable: true,
    label: 'Телефон',
    placeholder: 'Введите номер телефона',
  },
  email: {
    type: 'TEXT',
    nullable: true,
    label: 'Email',
    placeholder: 'Введите email',
  },
  link_table: {
    type: 'TEXT',
    nullable: true,
    label: 'Ссылка',
    placeholder: 'Введите ссылку',
  },
  bitrix: {
    type: 'TEXT',
    nullable: true,
    label: 'Bitrix',
    placeholder: 'Введите bitrix',
  },
  address: {
    type: 'TEXT',
    nullable: true,
    label: 'Адрес',
    placeholder: 'Введите адрес',
  },
  passport: {
    type: 'TEXT',
    nullable: true,
    label: 'Паспорт',
    placeholder: 'Введите паспортные данные',
  },
  relevance: {
    type: 'BOOLEAN',
    nullable: true,
    defaultValue: 'true',
    label: 'Актуальность',
    fieldType: 'switch',
  },
  login: {
    type: 'TEXT',
    nullable: true,
    label: 'Логин',
    placeholder: 'Введите логин',
  },
  password: {
    type: 'TEXT',
    nullable: true,
    label: 'Пароль',
    placeholder: 'Введите пароль',
    fieldType: 'password',
  },
  city: {
    type: 'UUID',
    nullable: true,
    label: 'Город',
    fieldType: 'select',
    relation: {
      table: 'city',
      value: 'id_city',
      label: 'name',
      through: {
        table: 'client_citys',
        foreignKey: 'id_city',
        relationKey: 'id_client',
      },
    },
  },
  services: {
    type: 'UUID',
    nullable: true,
    label: 'Сервисы',
    fieldType: 'multiselect',
    relation: {
      table: 'service',
      value: 'id_service',
      label: 'name',
      through: {
        table: 'client_services',
        foreignKey: 'id_service',
        relationKey: 'id_client',
      },
    },
  },
};
